from django.urls import include, path
from clinic import HodViews

urlpatterns = [
    path('bank-accounts/', HodViews.bank_account_list, name='bank_account_list'),    
    path('payrolls/', HodViews.payroll_list, name='payroll_list'),
    path('payment-methods/', HodViews.payment_method_list, name='payment_method_list'),
    path('expense-categories/', HodViews.expense_category_list, name='expense_category_list'), 
    path('deduction-organizations/', HodViews.deduction_organization_list, name='deduction_organization_list'), 
    path('employees/', HodViews.employee_list, name='employee_list'), 
    path('salary-payments/', HodViews.salary_payment_list, name='salary_payment_list'), 
    path('employee-deductions/', HodViews.employee_deduction_list, name='employee_deduction_list'),
    path('salary-change-records/', HodViews.salary_change_record_list, name='salary_change_record_list'),
    path('payments/', HodViews.payment_list, name='payment_list'),
    path('clients/', HodViews.client_list, name='client_list'),
    path('invoices/', HodViews.invoice_list, name='invoice_list'),
    
    path('add-bank-account/', HodViews.add_bank_account, name='add_bank_account'),
    path('delete_bank/<int:account_id>/', HodViews.delete_bank_account, name='delete_bank_account'),
    path('edit_bank_account/<int:bank_account_id>/', HodViews.add_bank_account, name='edit_bank_account'),
    path('add-payroll/', HodViews.add_payroll, name='add_payroll'),
    path('edit_payroll/<int:payroll_id>/', HodViews.add_payroll, name='edit_payroll'),
    path('delete_payroll/<int:payroll_id>/', HodViews.delete_payroll, name='delete_payroll'),
    path('add-payment-method/', HodViews.add_payment_method, name='add_payment_method'),
    path('edit_payment_method/<int:payment_method_id>/', HodViews.add_payment_method, name='edit_payment_method'),
    path('delete_payment_method/<int:payment_method_id>/', HodViews.delete_payment_method, name='delete_payment_method'),
    path('add-expense-category/', HodViews.add_expense_category, name='add_expense_category'),
    path('delete-expense-category/<int:expense_category_id>/', HodViews.delete_expense_category, name='delete_expense_category'),
    path('edit_expense_category/<int:expense_category_id>/', HodViews.add_expense_category, name='edit_expense_category'),
    path('add-expense/', HodViews.add_expense, name='add_expense'),
    path('expenses/add/', HodViews.add_expense, name='add_expense'),
    path('expenses/edit/<int:expense_id>/', HodViews.add_expense, name='edit_expense'),
    path('expenses/delete/<int:expense_id>/', HodViews.delete_expense, name='delete_expense'),
    path('employees/add/', HodViews.add_employee, name='add_employee'),
    path('employees/edit/<int:employee_id>/', HodViews.add_employee, name='edit_employee'),
    path('employees/delete/<int:employee_id>/', HodViews.delete_employee, name='delete_employee'),
    path('expenses/', HodViews.expense_list, name='expense_list'),
    path('add-payment/', HodViews.add_payment, name='add_payment'),
    path('add-client/add/', HodViews.add_client, name='add_client'),  
    path('add-client/edit/<int:client_id>/', HodViews.add_client, name='edit_client'),  
    path('salary_payments/add/', HodViews.add_salary_payment, name='add_salary_payment'),
    path('salary_payments/edit/<int:payment_id>/', HodViews.add_salary_payment, name='edit_salary_payment'),
    path('salary_payments/delete/<int:payment_id>/', HodViews.delete_salary_payment, name='delete_salary_payment'),
    path('add-deduction-organization/', HodViews.add_deduction_organization, name='add_deduction_organization'),
    path('edit-deduction-organization/<int:deduction_organization_id>/', HodViews.add_deduction_organization, name='edit_deduction_organization'),
    path('delete-deduction-organization/<int:deduction_organization_id>/', HodViews.delete_deduction_organization, name='delete_deduction_organization'),
    path('delete_employee_deduction/<int:deduction_id>/', HodViews.delete_employee_deduction, name='delete_employee_deduction'),
    path('delete_salary_change_record/<int:record_id>/', HodViews.delete_salary_change_record, name='delete_salary_change_record'),
    path('delete-client/<int:client_id>/', HodViews.delete_client, name='delete_client'),
]
