
from django.urls import include, path, re_path

from clinic import  ReceptionistView, editView, imports



urlpatterns = [
        path('save_prescription/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_prescription, name='receptionist_save_prescription'),
        path('save_laboratory/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_laboratory, name='receptionist_save_laboratory'),
        path('save_remotereferral/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_remotereferral, name='receptionist_save_remotereferral'),
        path('save_remoteprocedure/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_remoteprocedure, name='receptionist_save_remoteprocedure'),
        path('save_observation/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_observation, name='receptionist_save_observation'),
        path('verify_prescriptions/', ReceptionistView.verify_prescriptions, name='receptionist_verify_prescriptions'),
        path('unverify_prescriptions/', ReceptionistView.unverify_prescriptions, name='receptionist_unverify_prescriptions'),
        path('issue_prescriptions/', ReceptionistView.issue_prescriptions, name='receptionist_issue_prescriptions'),
        path('unissue_prescriptions/', ReceptionistView.unissue_prescriptions, name='receptionist_unissue_prescriptions'),        
        path('update_payment_status/', ReceptionistView.update_payment_status, name='receptionist_pay_prescriptions'),
        path('unpay_prescriptions/', ReceptionistView.unpay_prescriptions, name='receptionist_unpay_prescriptions'),
        path('add_investigation/', ReceptionistView.add_investigation, name='receptionist_add_investigation'),
        path('receptionist/get-gender-yearly-data/', ReceptionistView.get_gender_yearly_data, name="receptionist_get_gender_yearly_data"),
        path('receptionist/get-gender-monthly-data/', ReceptionistView.get_gender_monthly_data, name="receptionist_get_gender_monthly_data"),
        path('add_imaging/', ReceptionistView.add_imaging, name='receptionist_add_imaging'),
        path('ambulance_order/', ReceptionistView.ambulance_order_create_or_update, name='receptionist_ambulance_order_create_or_update'),
        path('ambulance_order/<int:order_id>/', ReceptionistView.ambulance_order_create_or_update, name='receptionist_ambulance_order_edit'),
        path('update_orderpayment_status/', ReceptionistView.update_orderpayment_status, name='receptionist_update_orderpayment_status'),
        path('invoice/<int:patient_id>/<int:visit_id>/', ReceptionistView.generate_invoice_bill, name='receptionist_generate_invoice_bill'),
        path('prescriptions/<str:visit_number>/<int:patient_id>/', ReceptionistView.prescription_detail, name='receptionist_prescription_detail'),
        path('prescription-billing/<str:visit_number>/<int:patient_id>/', ReceptionistView.prescription_billing, name='receptionist_prescription_billing'),
        path('prescription-notes/<str:visit_number>/<int:patient_id>/', ReceptionistView.prescription_notes, name='receptionist_prescription_notes'),
        path('patients/<int:patient_id>/visits/<int:visit_id>/ambulance_order/', ReceptionistView.save_ambulance_order, name='save_ambulance_order'),
        path('patients/<int:patient_id>/visits/<int:visit_id>/ambulance_order/<int:ambulance_id>/', ReceptionistView.save_ambulance_order, name='edit_ambulance_order'),
        path('add_consultation/', ReceptionistView.add_consultation, name='receptionist_add_consultation'),
        path('add_procedure/', ReceptionistView.add_procedure, name='receptionist_add_procedure'),
        path('get-procedure-cost/', ReceptionistView.get_procedure_cost, name='receptionist_get_procedure_cost'),   
        path('receptionist_dashboard/', ReceptionistView.receptionist_dashboard, name='receptionist_dashboard'),    
        path('receptionist/profile/', ReceptionistView.receptionist_profile, name='receptionist_profile'),
        path('resa/receptionist/change-password/', ReceptionistView.change_password, name='receptionist_change_password'),
        path('edit-profile/<int:pk>/', ReceptionistView.EditStaffProfileView.as_view(), name='receptionist_edit_staff_profile'),
        path('add_patient/', ReceptionistView.add_patient, name='receptionist_add_patient'),
        path('delete_ambulancecardorder/', ReceptionistView.delete_ambulancecardorder, name='receptionist_delete_ambulancecardorder'),
        path('delete_ambulancedorder/', ReceptionistView.delete_ambulancedorder, name='delete_ambulancedorder'),
        path('vehicle_detail/<int:order_id>/', ReceptionistView.vehicle_detail, name='receptionist_vehicle_detail'),    
        path('vehicle_ambulance_view/',ReceptionistView.vehicle_ambulance_view, name="receptionist_vehicle_ambulance_view"),        
        path('ambulance_order_detail/<int:order_id>/', ReceptionistView.ambulance_order_detail, name='receptionist_ambulance_order_detail'),        
        path('get_unit_price/',ReceptionistView.get_unit_price, name="receptionist_get_unit_price"),
        path('ambulance_order_view/',ReceptionistView.ambulance_order_view, name="receptionist_ambulance_order_view"),     
        path('add_remoteprescription/',ReceptionistView.add_remoteprescription, name="receptionist_add_remoteprescription"),
        path('save_patient_vital/',ReceptionistView.save_patient_vital, name="receptionist_save_patient_vital"),
        path('add_prescription/',ReceptionistView.add_prescription, name="receptionist_add_prescription"),
        path('save_edited_patient/',ReceptionistView.save_edited_patient, name="receptionist_save_edited_patient"),
        path('add_patient_visit/',ReceptionistView.add_patient_visit, name="receptionist_add_patient_visit"),      
        re_path(r'^receptionist/manage-pathodology/$', ReceptionistView.manage_pathodology, name='receptionist_manage_pathodology'),
        re_path(r'^receptionist/health-record-list/$', ReceptionistView.health_record_list, name='receptionist_health_record_list'),
        re_path(r'^receptionist/medicine-list/$', ReceptionistView.medicine_list, name='receptionist_medicine_list'),
        re_path(r'^receptionist/reagent-list/$', ReceptionistView.reagent_list, name='receptionist_reagent_list'),
        re_path(r'^receptionist/diagnosis-list/$', ReceptionistView.diagnosis_list, name='receptionist_diagnosis_list'),
        re_path(r'^receptionist/manage-disease/$', ReceptionistView.manage_disease, name='receptionist_manage_disease'),      
        path('staff_detail/<int:staff_id>/', ReceptionistView.single_staff_detail, name='receptionist_single_staff_detail'),
        path('patient/<int:patient_id>/', ReceptionistView.patient_detail, name='receptionist_patient_detail'),
        path('view-patient/<int:patient_id>/', ReceptionistView.view_patient, name='receptionist_view_patient'),  
        path('save_service_data/',ReceptionistView.save_service_data, name="receptionist_save_service_data"),      
        path('get_item_quantity/',ReceptionistView.get_item_quantity, name="receptionist_get_item_quantity"),  
        path('resa/patient_vital_all_listt/', ReceptionistView.patient_vital_all_list, name='receptionist_patient_vital_all_list'),
        path('patient_consultation_detail/<int:patient_id>/<int:visit_id>/', ReceptionistView.patient_consultation_detail, name='receptionist_patient_consultation_detail'),
        path('patient/<int:patient_id>/visit/<int:visit_id>/', ReceptionistView.patient_visit_details_view, name='receptionist_patient_visit_details_view'),
        path('patient_health_record/<int:patient_id>/<int:visit_id>/', ReceptionistView.patient_health_record, name='receptionist_patient_health_record'),
        path('patient_vital_visit_list/<int:patient_id>/<int:visit_id>/', ReceptionistView.patient_vital_visit_list, name='receptionist_patient_vital_visit_list'),
        path('patient_visit_history/<int:patient_id>/', ReceptionistView.patient_visit_history_view, name='receptionist_patient_visit_history_view'),       
        path('prescriptions/', ReceptionistView.prescription_list, name='receptionist_prescription_list'),       
        path('resa/manage-referral/', ReceptionistView.manage_referral, name='receptionist_manage_referral'),
        path('resa/patient-procedure-view/', ReceptionistView.patient_procedure_view, name='receptionist_patient_procedure_view'),      
        path('resa/all-patients',ReceptionistView.manage_patients, name="receptionist_manage_patients"),
        path('resa/save/remotepatient/vital',ReceptionistView.save_remotepatient_vital, name="receptionist_save_remotepatient_vital"),
        path('resa/consultation-queue',ReceptionistView.manage_consultation, name="receptionist_manage_consultation"),
        path('resa/manage-service',ReceptionistView.manage_service, name="receptionist_manage_service"),
        path('employee/', ReceptionistView.employee_detail, name='receptionist_employee_detail'),
        path('resa/appointments/', ReceptionistView.appointment_list_view, name='receptionist_appointment_list'),       
        path('generate-bill/<int:procedure_id>/', ReceptionistView.generate_billing, name='receptionist_generate_billing'),
        path('save_procedure/', ReceptionistView.save_procedure, name='receptionist_save_procedure'),
        path('save_referral/', ReceptionistView.save_referral, name='receptionist_save_referral'),
        path('all_orders_view/', ReceptionistView.all_orders_view, name='receptionist_all_orders_view'),
        path('change_referral_status/', ReceptionistView.change_referral_status, name='receptionist_change_referral_status'),       
        # imports urls 
        
        path('resa/ImportExcel_service',imports.import_service_records, name="receptionist_import_service_records"),     
        path('import_prescription_records', imports.import_prescription_records, name='receptionist_import_prescription_records'),
        path('import-patients/', imports.import_patient_records, name='receptionist_import_patient_records'),    
        path('import-procedure-records/', imports.import_procedure_records, name='receptionist_import_procedure_records'),
        path('import-referral-records/', imports.import_referral_records, name='receptionist_import_referral_records'), 
             
        # edit urls        
        path('update_consultation_data/<int:appointment_id>/', editView.update_consultation_data, name='receptionist_update_consultation_data'), 
        path('Patient/<int:patient_id>/edit/', editView.edit_patient, name='receptionist_edit_patient'),
        path('edit_procedure/', editView.edit_procedure, name='receptionist_edit_procedure'), 
        path('edit_referral/', editView.edit_referral, name='receptionist_edit_referral'), 
        path('appointment_view/', ReceptionistView.appointment_view, name='receptionist_appointment_view'), 
        path('patient-procedure-history/<str:mrn>/view/', ReceptionistView.patient_procedure_history_view, name='receptionist_patient_procedure_history_view_mrn'), 

        path('patient_laboratory_view/', ReceptionistView.patient_laboratory_view, name="receptionist_patient_laboratory_view"), 
        path('patient_lab_result_history_view/<str:mrn>/view/', ReceptionistView.patient_lab_result_history_view, name="receptionist_patient_lab_result_history_view"), 
        path('lab-details/<str:mrn>/<str:visit_number>/', ReceptionistView.patient_lab_details_view, name='receptionist_patient_lab_details_view'),
        path('resa/patient-procedure-view/', ReceptionistView.patient_procedure_view, name='receptionist_patient_procedure_view'),   
        path('procedure/detail/<str:mrn>/<str:visit_number>/', ReceptionistView.patient_procedure_detail_view, name='receptionist_patient_procedure_detail_view'),  
        path('resa/manage-referral/', ReceptionistView.manage_referral, name='receptionist_manage_referral'), 
        path('referral/view/<int:referral_id>/',ReceptionistView.view_referral, name='receptionist_view_referral'),
        path('counseling/', ReceptionistView.counseling_list_view, name='receptionist_counseling_list'),
        path('save_counsel/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_counsel, name='kahama_save_remote_counseling'),
        path('counseling_notes/<int:patient_id>/<int:visit_id>/', ReceptionistView.view_counseling_notes, name='kahama_view_counseling_notes'),
        path('discharge_notes/', ReceptionistView.discharge_notes_list_view, name='receptionist_discharge_notes_list'),
        path('save_remote_discharges_notes/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_remote_discharges_notes, name='receptionist_save_remote_discharges_notes'),
        path('discharge/details/<int:patient_id>/<int:visit_id>/', ReceptionistView.discharge_details_view, name='receptionist_discharge_details_view'),
        path('observation_records/', ReceptionistView.observation_record_list_view, name='receptionist_observation_record_list'),
        path('save_observation/<int:patient_id>/<int:visit_id>/', ReceptionistView.save_observation, name='receptionist_save_observation'),
        path('observation_notes/<int:patient_id>/<int:visit_id>/', ReceptionistView.view_observation_notes, name='receptionist_view_observation_notes'),
        path('consultation-notes/', ReceptionistView.consultation_notes_view, name='receptionist_consultation_notes'),

]
