# Generated by Django 4.2.9 on 2025-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembahmis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembapatient',
            name='date_of_ftw_certification',
            field=models.DateField(blank=True, help_text='Date of FTW certification.', null=True),
        ),
        migrations.AddField(
            model_name='pembapatient',
            name='ftw_certificate',
            field=models.BooleanField(default=False, help_text='Whether the patient has an FTW certificate.'),
        ),
    ]
