# Generated by Django 4.2.9 on 2025-09-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_prescription_dosage_prescription_route_and_more'),
        ('pembahmis', '0002_pembapatient_date_of_ftw_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembaconsultationnotes',
            name='allergy_summary',
        ),
        migrations.RemoveField(
            model_name='pembaconsultationnotes',
            name='known_comorbidities_summary',
        ),
        migrations.RemoveField(
            model_name='pembapatientvital',
            name='avpu',
        ),
        migrations.AddField(
            model_name='pembapatientvital',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body Mass Index (BMI).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pembapatientvital',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pembapatientvital',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pembaconsultationnotes',
            name='patient',
            field=models.ForeignKey(help_text='Patient for whom the notes are written.', on_delete=django.db.models.deletion.CASCADE, related_name='pemba_consultation_notes', to='pembahmis.pembapatient'),
        ),
        migrations.AlterField(
            model_name='pembaconsultationnotes',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='Visit associated with the consultation notes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pemba_consultation_notes', to='pembahmis.pembapatientvisits'),
        ),
        migrations.AlterField(
            model_name='pembapatientvital',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who recorded the vitals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_pemba_vitals', to='clinic.staffs'),
        ),
        migrations.AlterField(
            model_name='pembapatientvital',
            name='patient',
            field=models.ForeignKey(help_text='Patient whose vitals are recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='pemba_vitals', to='pembahmis.pembapatient'),
        ),
        migrations.AlterField(
            model_name='pembapatientvital',
            name='visit',
            field=models.ForeignKey(help_text='Visit during which vitals were recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='pemba_vitals', to='pembahmis.pembapatientvisits'),
        ),
        migrations.CreateModel(
            name='PembaDiseaseRecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pemba_disease_records', to='clinic.staffs')),
            ],
        ),
    ]
