# Generated by Django 4.2.9 on 2025-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembahmis', '0003_remove_pembaconsultationnotes_allergy_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembapatientsurgery',
            name='surgery_date',
            field=models.CharField(blank=True, help_text='Date when the surgery was performed.', max_length=100, null=True),
        ),
    ]
