# Generated by Django 4.2.9 on 2025-09-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembahmis', '0004_alter_pembapatientsurgery_surgery_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PembaImagingRecord',
        ),
    ]
