
from django.urls import include, path
from kahamahmis import KahamaReportsView, kahamaExcelTemplate, kahamaViews
from . import kahamaImports, views,delete,editView

urlpatterns = [  
        path('generate_comprehensive_report/', KahamaReportsView.generate_comprehensive_report, name='generate_comprehensive_report'),
        path('company/add/', kahamaViews.company_registration_view, name='add_clinc_company'),    # URL for editing an existing company
        path('company/edit/<int:company_id>/', kahamaViews.company_registration_view, name='edit_clinic_company'),
        path('get_formulation_unit/', kahamaViews.get_formulation_unit, name='get_formulation_unit'),
        path('get_medicine_formulation/', kahamaViews.get_medicine_formulation, name='get_medicine_formulation'),
        path('add_remote_medicine/', kahamaViews.add_remote_medicine, name='add_remote_medicine'),
        path('remotemedicine_list/', kahamaViews.remotemedicine_list, name='remotemedicine_list'),
        path('search_report/', kahamaViews.search_report, name='search_report'),  
        path('patient_statistics/', kahamaViews.patient_statistics, name='patient_statistics'),
        path('add_service/', kahamaViews.add_service, name='add_service'),
        path('delete_remote_patient/<int:patient_id>/', kahamaViews.delete_remote_patient, name='delete_remote_patient'),
        path('get_unit_price/', kahamaViews.get_unit_price, name='get_unit_price'),
        path('get_medicine_dosage/', kahamaViews.medicine_dosage, name='medicine_dosage'),
        path('appointment_view/', kahamaViews.appointment_view, name='appointment_view'), 
        path('get_drug_division_status/', kahamaViews.get_drug_division_status, name='get_drug_division_status'),
        path('verify_prescriptions/', kahamaViews.verify_prescriptions, name='verify_prescriptions'),
        path('unverify_prescriptions/', kahamaViews.unverify_prescriptions, name='unverify_prescriptions'),
        path('issue_prescriptions/', kahamaViews.issue_prescriptions, name='issue_prescriptions'),
        path('unissue_prescriptions/', kahamaViews.unissue_prescriptions, name='unissue_prescriptions'),        
        path('update_payment_status/', kahamaViews.update_payment_status, name='pay_prescriptions'),
        path('unpay_prescriptions/', kahamaViews.unpay_prescriptions, name='unpay_prescriptions'),
        path('remote-equipment/', kahamaViews.remote_equipment_list, name='remote_equipment_list'),
        path('add-remote-equipment/', kahamaViews.add_or_edit_remote_equipment, name='add_or_edit_remote_equipment'),
        path('patient_observation_history_view/<str:mrn>/view/',kahamaViews.patient_observation_history_view, name="patient_observation_history_view"),
        path('patient_lab_result_history_view/<str:mrn>/view/',kahamaViews.patient_lab_result_history_view, name="patient_lab_result_history_view"),
        path('add_remoteprescription/',kahamaViews.add_remoteprescription, name="add_remoteprescription"),
        path('reagent_list/',kahamaViews.reagent_list, name="reagent_list"),
        path('add_or_edit_reagent/',kahamaViews.add_or_edit_reagent, name="add_or_edit_reagent"),
        path('patient_laboratory_view/',kahamaViews.patient_laboratory_view, name="patient_laboratory_view"),
        path('patient_observation_view/',kahamaViews.patient_observation_view, name="patient_observation_view"),
        path('get-frequency-name/', kahamaViews.get_frequency_name, name='get_frequency_name'),
        path('counsel/<int:patient_id>/<int:visit_id>/', kahamaViews.save_counsel, name='save_remote_counseling'),
        path('laboratory/<int:patient_id>/<int:visit_id>/', kahamaViews.save_laboratory, name='save_laboratory'),
        path('observation/<int:patient_id>/<int:visit_id>/', kahamaViews.save_observation, name='save_observation'),
        path('save_remoteprocedure/<int:patient_id>/<int:visit_id>/', kahamaViews.save_remoteprocedure, name='save_remoteprocedure'),
        path('save_remotereferral/<int:patient_id>/<int:visit_id>/', kahamaViews.save_remotereferral, name='save_remotereferral'),
        path('save_remote_discharges_notes/<int:patient_id>/<int:visit_id>/', kahamaViews.save_remote_discharges_notes, name='save_remote_discharges_notes'),
        path('add_primary_physical_examination/', kahamaViews.add_primary_physical_examination, name='add_primary_physical_examination'),
        path('save_chief_complaint/', kahamaViews.save_chief_complaint, name='save_chief_complaint'),
        path('delete_chief_complaint/<int:chief_complaint_id>/', kahamaViews.delete_chief_complaint, name='delete_chief_complaint'),   
        path('fetch-existing-data/', kahamaViews.fetch_existing_data, name='endpoint_to_fetch_existing_data'),       
        path('get_chief_complaints/', kahamaViews.get_chief_complaints, name='get_chief_complaints'),          
        path('delete_healthrecord/', kahamaViews.delete_healthrecord, name='delete_healthrecord'),          
        path('delete_reagent',kahamaViews.delete_reagent, name="delete_reagent"),  
        path('health_record_list',kahamaViews.health_record_list, name="health_record_list"),  
        path('delete_remote_equipment/', kahamaViews.delete_remote_equipment, name='delete_remote_equipment'),         
        path('save_health_record',kahamaViews.save_health_record, name="save_health_record"),     
        path('edit_procedure_result/<int:patient_id>/<int:visit_id>/<int:procedure_id>/', kahamaViews.edit_procedure_result, name='edit_procedure_result'),
        path('edit_lab_result/<int:patient_id>/<int:visit_id>/<int:lab_id>/', kahamaViews.edit_lab_result, name='edit_lab_result'),      
        path('save_patient_health_information/<int:patient_id>/',kahamaViews.save_patient_health_information, name="save_patient_health_information"),
        path('get_patient_data_by_company',views.get_patient_data_by_company, name="get_patient_data_by_company"),
        path('get_gender_yearly_data',views.get_gender_yearly_data, name="get_gender_yearly_data"),
        path('get_gender_monthly_data',views.get_gender_monthly_data, name="get_gender_monthly_data"),
        
       
        path('manage_country',views.manage_country, name="manage_country"),
        path('add_remote_consultation',views.add_remote_consultation, name="add_remote_consultation"),
        path('save_remote_service',views.save_remote_service, name="save_remote_service"),              
        path('save_patient_visit_save/<int:patient_id>/',views.save_patient_visit_save, name="save_patient_visit_save"),      
        path('individual_visit/<int:patient_id>/',views.individual_visit, name="individual_visit"),             
        path('patient_info_form_edit/<int:patient_id>/',views.patient_info_form_edit, name="patient_info_form_edit"),
        path('health_info_edit/<int:patient_id>/',views.health_info_edit, name="health_info_edit"),        
        path('patient_info_form/',views.patient_info_form, name="patient_info_form"),
        path('patient_info_form/<int:patient_id>/', views.patient_info_form, name='edit_patient'),        
        path('save_diagnosis/',views.save_diagnosis, name="save_diagnosis"),       
    
        path('save_remotesconsultation_notes/<int:patient_id>/<int:visit_id>/',kahamaViews.save_remotesconsultation_notes, name="save_remotesconsultation_notes"),
        path('save_remotesconsultation_notes_next/<int:patient_id>/<int:visit_id>/',kahamaViews.save_remotesconsultation_notes_next, name="save_remotesconsultation_notes_next"),
    
        path('save_nextprescription/<int:patient_id>/<int:visit_id>/', views.save_nextprescription, name='nextsave_prescription'),
        path('prescription/<int:patient_id>/<int:visit_id>/', views.save_prescription, name='save_prescription'),
        path('save_nextlaboratory/<int:patient_id>/<int:visit_id>/', views.save_nextlaboratory, name='nextsave_laboratory'),
        
        path('nextsave_remotereferral/<int:patient_id>/<int:visit_id>/', views.save_nextremotereferral, name='nextsave_remotereferral'),        
        path('save_nextcounsel/<int:patient_id>/<int:visit_id>/', views.save_nextcounsel, name='nextsave_counsel'),        
        path('save_nextremoteprocedure/<int:patient_id>/<int:visit_id>/', views.save_nextremoteprocedure, name='nextsave_remoteprocedure'),
        
        path('save_nextobservation/<int:patient_id>/<int:visit_id>/', views.save_nextobservation, name='nextsave_observation'),        
 
        path('save_remotepatient_vital/',views.save_remotepatient_vital, name="save_remotepatient_vital"),       
        path('resa/dashboard',views.kahama_dashboard, name="dashboard"),
        path('resa/ImportExcel',views.import_staff, name="import_staff"),      
        path('add_disease/', views.add_disease, name='add_disease'),
        path('add_insurance_company/', views.add_insurance_company, name='add_insurance_company'),
        path('add_company/', views.add_company, name='add_company'),
        path('add_pathodology_record/', views.add_pathodology_record, name='add_pathodology_record'),          
        path('kahama_login', views.ShowLoginKahama, name='kahama'),        
        path('logout_user', views.logout_user, name='logout_user'),  # Move this line here
        path('contact/', views.ContactFormView.as_view(), name='contact_form'),
        path('GetUserDetails', views.GetUserDetails, name='GetUserDetails'),
        path('DoLoginKahama', views.DoLoginKahama, name='DoLoginKahama'),      
        path('accounts/', include('django.contrib.auth.urls')),  
        path('resa/portfolio/details',views.portfolio_details, name="portfolio_details"),
        path('resa/contact',views.contact, name="contact"),
        path('resa/blog/single',views.blog_single, name="blog_single"),
        path('resa/page/404',views.page_404, name="page_404"),       

        path('staff_detail/<int:staff_id>/', views.single_staff_detail, name='single_staff_detail'),     
        path('save_remotepatient_vitals/<int:patient_id>/<int:visit_id>/', views.save_remotepatient_vitals, name='save_remotepatient_vitals'),
        path('view-patient/<int:patient_id>/', views.view_patient, name='view_patient'),
        path('edit_staff/<str:staff_id>', views.edit_staff, name='edit_staff'),  
        path('edit_staff_save', views.edit_staff_save, name='edit_staff_save'),      
        path('resa/update-staff-status',views.update_staff_status, name="update_staff_status"),      
        path('save_staff_view/',views.save_staff_view, name="save_staff_view"),    
        path('save_consultation_data/',views.save_consultation_data, name="save_consultation_data"), 
        
        # reports urls 
        path('resa/resa-report',views.resa_report, name="resa_report"),       
        path('resa/reports-adjustments',views.reports_adjustments, name="reports_adjustments"),
        path('resa/reports-by-visit',views.reports_by_visit, name="reports_by_visit"),
        path('resa/reports-comprehensive',views.reports_comprehensive, name="reports_comprehensive"),
        path('resa/reports-patients-visit_summary',views.reports_patients_visit_summary, name="reports_patients_visit_summary"),
        path('resa/reports-patients',views.reports_patients, name="reports_patients"),
        path('resa/reports-service',views.reports_service, name="reports_service"),
        path('resareports-stock-ledger',views.reports_stock_ledger, name="reports_stock_ledger"),
        path('resa/reports-stock-level',views.reports_stock_level, name="reports_stock_level"),
        path('resa/reports-orders',views.reports_orders, name="reports_orders"),
        path('resa/individual-visit',views.individual_visit, name="individual_visit"),
        path('resa/product-summary',views.product_summary, name="product_summary"),        
    
        
       
        
        # manage urls        
        path('patients/', views.patients_list, name='patients_list'),
        path('diagnosis/', views.diagnosis_list, name='diagnosis_list'),
        path('generatePDF/<int:patient_id>/<int:visit_id>/', views.generatePDF, name='generatePDF'),
        path('remoteservice_list/', views.remoteservice_list, name='remoteservice_list'),
        path('consultation-notes/', views.consultation_notes_view, name='consultation_notes'),
        path('resa/patient_vital_all_listt/', views.patient_vital_all_list, name='patient_vital_all_list'),
     
        path('patient_vital_list/<int:patient_id>/<int:visit_id>/', views.patient_vital_list, name='patient_vital_list'),
        path('patient_visit_details_view/<int:patient_id>/<int:visit_id>/', views.patient_visit_details_view, name='patient_visit_details_view'),
        path('patient_health_record_view/<int:patient_id>/<int:visit_id>/', views.patient_health_record_view, name='patient_health_record_view'),
        path('patient_visit_history/<int:patient_id>/', views.patient_visit_history_view, name='patient_visit_history_view'),
        path('prescriptions/<str:visit_number>/<int:patient_id>/', views.prescription_detail, name='prescription_detail'),
        path('prescription-billing/<str:visit_number>/<int:patient_id>/', views.prescription_billing, name='prescription_billing'),
        path('prescription-notes/<str:visit_number>/<int:patient_id>/', views.prescription_notes, name='prescription_notes'),
      
        path('prescriptions/', views.prescription_list, name='prescription_list'),
        path('counseling/', views.counseling_list_view, name='counseling_list'),
        path('discharge_notes/', views.discharge_notes_list_view, name='discharge_notes_list'),
        path('observation_records/', views.observation_record_list_view, name='observation_record_list'),
     
        path('resa/manage-referral/', views.manage_referral, name='manage_referral'),
        path('resa/patient-procedure-view/', views.patient_procedure_view, name='patient_procedure_view'),
   
      
        path('out_of_stock_medicines_view/', views.out_of_stock_medicines_view, name='out_of_stock_medicines_view'),       
        path('resa/all-patients',views.manage_patient, name="manage_patient"),
        path('resa/consultation-queue',views.manage_consultation, name="manage_consultation"),     
        path('resa/manage-company',views.manage_company, name="manage_company"),
        path('resa/manage-disease',views.manage_disease, name="manage_disease"),      
        path('resa/manage-staff',views.manage_staff, name="manage_staff"),
        path('resa/manage-insurance',views.manage_insurance, name="manage_insurance"),       
        path('resa/manage-adjustment',views.manage_adjustment, name="manage_adjustment"),
        path('resa/manage-pathodology',views.manage_pathodology, name="manage_pathodology"),
        path('resa/appointments/', views.appointment_list_view, name='appointment_list'),
        path('in_stock_medicines_view/', views.in_stock_medicines_view, name='in_stock_medicines_view'),         
        path('confirm_meeting/<int:appointment_id>/', views.confirm_meeting, name='confirm_meeting'),
        path('generate-bill/<int:procedure_id>/', views.generate_billing, name='generate_billing'),
        path('edit_meeting/<int:appointment_id>/', views.edit_meeting, name='edit_meeting'),
        path('resa/medicine-expired-list/', views.medicine_expired_list, name='medicine_expired_list'),     
        path('save_referral/', views.save_referral, name='save_referral'),        
        path('change_referral_status/', views.change_referral_status, name='change_referral_status'),
        path('api/out-of-stock-medicines/', views.out_of_stock_medicines, name='out_of_stock_medicines'),     
      
     
        path('disease-records/<int:disease_id>/edit/', editView.edit_disease_record, name='edit_disease_record'),
        path('insurance-records/<int:insurance_id>/edit/', editView.edit_insurance, name='edit_insurance'),
        path('pathodology/<int:pathodology_id>/edit/', editView.edit_pathodology, name='edit_pathodology'),
        path('company/<int:company_id>/edit/', editView.edit_company, name='edit_company'),
        path('update_consultation_data/<int:appointment_id>/', editView.update_consultation_data, name='update_consultation_data'), 
      
        path('edit_procedure/', editView.edit_procedure, name='edit_procedure'), 
        path('edit_lab_result/', editView.edit_lab_result, name='edit_lab_result'), 
        path('edit_observation/', editView.edit_observation, name='edit_observation'), 
        path('edit_referral/', editView.edit_referral, name='edit_referral'),   
        path('patient-procedure-history/<str:mrn>/view/', views.patient_procedure_history_view, name='patient_procedure_history_view_mrn'), 
        path('edit_medicine/<int:medicine_id>/', editView.edit_medicine, name='edit_medicine'),        
        path('edit_inventory/<int:inventory_id>/', editView.edit_inventory, name='edit_inventory'),
       
        
        # delete urls 
        
        
        path('delete_diagnosis/', delete.delete_diagnosis, name='delete_diagnosis'),
        path('delete_ConsultationNotes/<int:consultation_id>/', delete.delete_ConsultationNotes, name='delete_ConsultationNotes'),
        path('delete_patient_vital/<int:vital_id>/', delete.delete_patient_vital, name='delete_patient_vital'),
        path('delete_prescription/<int:prescription_id>/', delete.delete_prescription, name='delete_prescription'),
        path('delete-consultation/<int:appointment_id>/', delete.delete_consultation, name='delete_consultation'),
        path('delete_medicine/<int:medicine_id>/', delete.delete_medicine, name='delete_medicine'),
        path('disease-records/<int:disease_id>/delete/', delete.delete_disease_record, name='delete_disease_record'),                   
        path('insurance-records/<int:insurance_id>/delete/', delete.delete_insurance, name='delete_insurance'),        
        path('pathodology/<int:pathodology_id>/delete/', delete.delete_pathodology, name='delete_pathodology'),
        path('company/<int:company_id>/delete/', delete.delete_company, name='delete_company'),
        path('delete_staff/<int:staff_id>/', delete.delete_staff, name='delete_staff'),        
        path('delete-patient/<int:patient_id>/', delete.delete_patient, name='delete_patient'),
        path('delete_remoteinsurancecompany/', delete.delete_remoteinsurancecompany, name='delete_remoteinsurancecompany'),            
        path('delete_drug/', delete.delete_drug, name='delete_drug'),            
        path('delete_pathology_record/', delete.delete_pathology_record, name='delete_pathology_record'),            
        path('delete_service/', delete.delete_service, name='delete_service'),            
        path('delete_procedure/', delete.delete_procedure, name='delete_procedure'),        
        path('delete_result/', delete.delete_result, name='delete_result'),        
        path('delete_observation/', delete.delete_observation, name='delete_observation'),        
        path('delete_health_record/', delete.delete_health_record, name='delete_health_record'),        
        path('delete_medication_allergy_record/', delete.delete_medication_allergy_record, name='delete_medication_allergy_record'),        
        path('delete_surgery_history_record/', delete.delete_surgery_history_record, name='delete_surgery_history_record'),        
        path('delete_family_medical_history_record/', delete.delete_family_medical_history_record, name='delete_family_medical_history_record'),       
        path('delete_lab_result/', delete.delete_lab_result, name='delete_lab_result'),        
        path('delete_referral/', delete.delete_referral, name='delete_referral'),       
        path('delete_patient_visit/<int:patient_visit_id>/', delete.delete_patient_visit, name='delete_patient_visit'),
        
        # excel template
        path('download-disease-template/', kahamaExcelTemplate.download_disease_recode_excel_template, name='disease_recode_template_download'),
        path('download-health-template/', kahamaExcelTemplate.download_health_record_excel_template, name='health_record_template_download'),
        path('download-remote-company-template/', kahamaExcelTemplate.download_remote_company_excel_template, name='remote_company_template_download'),
        path('download-pathodology-template/', kahamaExcelTemplate.download_pathodology_record_excel_template, name='pathodology_record_template_download'),
        path('download-supplier-template/', kahamaExcelTemplate.download_supplier_excel_template, name='supplier_template_download'),
        path('download-category-template/', kahamaExcelTemplate.download_category_excel_template, name='category_template_download'),
        path('download-service-template/', kahamaExcelTemplate.download_service_excel_template, name='service_template_download'),
        path('download-insurance-company-template/', kahamaExcelTemplate.download_insurance_company_excel_template, name='insurance_company_template_download'),
        path('download-staffs-template/', kahamaExcelTemplate.download_staffs_excel_template, name='staffs_template_download'),
        path('download-prescription-frequency-template/', kahamaExcelTemplate.download_prescription_frequency_excel_template, name='prescription_frequency_template_download'),
        path('download-ambulance-route-template/', kahamaExcelTemplate.download_ambulance_route_excel_template, name='ambulance_route_template_download'),
        path('download-ambulance-vehicle-order-template/', kahamaExcelTemplate.download_ambulance_vehicle_order_excel_template, name='ambulance_vehicle_order_template_download'),
        path('download-hospital-vehicle-template/', kahamaExcelTemplate.download_hospital_vehicle_excel_template, name='hospital_vehicle_template_download'),
        path('download-remote-medicine-template/', kahamaExcelTemplate.download_remote_medicine_excel_template, name='remote_medicine_template_download'),
        path('download-remote-service-template/', kahamaExcelTemplate.download_remote_service_excel_template, name='remote_service_template_download'),
        path('download-country-template/', kahamaExcelTemplate.download_country_excel_template, name='download_country_template'), 
        path('download-remote-reagent-template/', kahamaExcelTemplate.download_remote_reagent_excel_template, name='download_remote_reagent_template'),
        path('download-remote-equipment-template/', kahamaExcelTemplate.download_remote_equipment_excel_template, name='download_remote_equipment_template'),
        path('download-diagnosis-template/', kahamaExcelTemplate.download_diagnosis_excel_template, name='download_diagnosis_template'),
        
           # imports urls 
        path('import_insurance_company_data', kahamaImports.import_insurance_company_data, name='import_insurance_company_data'),
        path('import-disease-data/', kahamaImports.import_disease_recode_data, name='import_disease_recode_data'),
        path('import-remote-medicine-data/', kahamaImports.import_remote_medicine_data, name='import_remote_medicine_data'),
        path('import-health-record-data/', kahamaImports.import_health_record_data, name='import_health_record_data'),
        path('import-remote-company-data/', kahamaImports.import_remote_company_data, name='import_remote_company_data'),
        path('import-pathodology-record-data/', kahamaImports.import_pathodology_record_data, name='import_pathodology_record_data'),
        path('import-remote-service-data/', kahamaImports.import_remote_service_data, name='import_remote_service_data'),
        path('import-country-data/', kahamaImports.import_country_data, name='import_country_data'),
        path('import-remote-reagent/', kahamaImports.import_remote_reagent_data, name='import_remote_reagent_data'),
        path('import-remote-equipment/', kahamaImports.import_remote_equipment_data, name='import_remote_equipment_data'),
        path('import-diagnosis-data/', kahamaImports.import_diagnosis_data, name='import_diagnosis_data'),
]       

