# Generated by Django 4.2.9 on 2025-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinprescription',
            name='dosage',
            field=models.CharField(blank=True, help_text='Human-readable dosage instructions', max_length=255, null=True),
        ),
    ]
