# Generated by Django 4.2.9 on 2024-05-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultation',
            name='pathodology_record',
        ),
    ]
