# Generated by Django 4.2.9 on 2025-09-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_walkinprescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinvisit',
            name='prescription_notes_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the prescription notes ID was generated.', null=True),
        ),
        migrations.AddField(
            model_name='walkinvisit',
            name='prescription_notes_id',
            field=models.CharField(blank=True, help_text='Auto-generated unique prescription notes ID for this visit.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='walkinvisit',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the receipt number was generated.', null=True),
        ),
        migrations.AddField(
            model_name='walkinvisit',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Unique receipt number generated when payment is processed.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='walkinprescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.walkinvisit'),
        ),
        migrations.AlterField(
            model_name='walkinvisit',
            name='customer',
            field=models.ForeignKey(help_text='The customer associated with this walk-in visit.', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.walkincustomer'),
        ),
        migrations.AlterField(
            model_name='walkinvisit',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes related to the visit.', null=True),
        ),
        migrations.AlterField(
            model_name='walkinvisit',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the visit was created.'),
        ),
        migrations.AlterField(
            model_name='walkinvisit',
            name='visit_number',
            field=models.CharField(editable=False, help_text='Unique visit number (auto-generated, e.g. VST-0000001).', max_length=12, unique=True),
        ),
    ]
