# Generated by Django 4.2.9 on 2024-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_remoteconsultation_pathodology_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
