# Generated by Django 4.2.9 on 2024-06-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_staffs_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
