# Generated by Django 4.2.9 on 2025-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_walkinvisit_prescription_notes_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, help_text='Human-readable dosage instructions (e.g., 1 tablet twice daily).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='route',
            field=models.CharField(blank=True, help_text='Route of administration (e.g., Oral, IV).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(help_text='Duration of the prescription treatment (e.g., 7 days).', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='formulation_dose',
            field=models.CharField(help_text='Dosage instructions for the medication (e.g., 500mg tablet).', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='issued',
            field=models.CharField(choices=[('issued', 'Issued'), ('not_issued', 'Not Issued')], default='not_issued', help_text='Whether the medication has been issued to the patient.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status of the prescription.', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='verified',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not Verified')], default='not_verified', help_text='Whether the prescription has been verified by a pharmacist.', max_length=20),
        ),
    ]
