# Generated by Django 4.2.9 on 2024-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_rename_client_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
