# Generated by Django 4.2.9 on 2024-06-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_remove_company_address_remove_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location_in_storage',
        ),
    ]
