# Generated by Django 4.2.9 on 2024-06-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_inventoryitem_location_in_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagentusage',
            old_name='technician_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='reagentusage',
            name='lab_technician',
        ),
        migrations.RemoveField(
            model_name='reagentusage',
            name='observation',
        ),
    ]
