# Generated by Django 4.2.9 on 2024-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_rename_technician_notes_reagentusage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvital',
            name='dbp',
            field=models.PositiveIntegerField(blank=True, help_text='Diastolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='sbp',
            field=models.PositiveIntegerField(blank=True, help_text='Systolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Respiratory rate in breaths per minute', null=True),
        ),
        migrations.AlterField(
            model_name='patientvital',
            name='spo2',
            field=models.PositiveIntegerField(blank=True, help_text='SPO2 measurement in percentage', null=True),
        ),
    ]
