# Generated by Django 4.2.9 on 2024-06-21 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_patientvital_dbp_patientvital_sbp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counseling',
            old_name='counselor',
            new_name='data_recorder',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='doctor',
            new_name='data_recorder',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='allergy_to_medications',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='chief_complaints',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='consultation_number',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='final_diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='physical_examination',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='provisional_diagnosis',
        ),
        migrations.RemoveField(
            model_name='counseling',
            name='description',
        ),
        migrations.RemoveField(
            model_name='counseling',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referral_date',
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='nature_of_current_illness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='type_of_illness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='counselling_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='nature_of_referral',
            field=models.CharField(choices=[('Med Evac', 'Med Evac'), ('Referred', 'Referral')], default='Referred', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='transport_model',
            field=models.CharField(choices=[('Ground Ambulance', 'Ground Ambulance'), ('Air Ambulance', 'Air Ambulance'), ('Private Vehicle', 'Private Vehicle'), ('Self Transport', 'Self Transport'), ('Company Walking', 'Company Walking'), ('Walking', 'Walking'), ('Motorcycle', 'Motorcycle'), ('Others', 'Others'), ('Unknown', 'Unknown')], default='Ground Ambulance', max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientDiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('final_diagnosis', models.ManyToManyField(related_name='final_diagnosis_record', to='clinic.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('provisional_diagnosis', models.ManyToManyField(related_name='provisional_diagnosis_record', to='clinic.diagnosis')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='DischargesNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_condition', models.CharField(max_length=255)),
                ('discharge_notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSecondaryPhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heent', models.CharField(blank=True, max_length=50, null=True)),
                ('cns', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_cns', models.CharField(blank=True, max_length=50, null=True)),
                ('abnormal_cns', models.CharField(blank=True, max_length=50, null=True)),
                ('cvs', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_cvs', models.CharField(blank=True, max_length=50, null=True)),
                ('abnormal_cvs', models.CharField(blank=True, max_length=50, null=True)),
                ('rs', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_rs', models.CharField(blank=True, max_length=50, null=True)),
                ('abnormal_rs', models.CharField(blank=True, max_length=50, null=True)),
                ('pa', models.CharField(blank=True, max_length=50, null=True)),
                ('normal_pa', models.CharField(blank=True, max_length=50, null=True)),
                ('abnormal_pa', models.CharField(blank=True, max_length=50, null=True)),
                ('gu', models.CharField(blank=True, max_length=100, null=True)),
                ('normal_gu', models.CharField(blank=True, max_length=100, null=True)),
                ('abnormal_gu', models.CharField(blank=True, max_length=100, null=True)),
                ('mss', models.CharField(blank=True, max_length=100, null=True)),
                ('normal_mss', models.CharField(blank=True, max_length=100, null=True)),
                ('abnormal_mss', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicPrimaryPhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airway', models.CharField(blank=True, max_length=200, null=True)),
                ('patent_airway', models.CharField(blank=True, max_length=200, null=True)),
                ('notpatient_explanation', models.TextField(blank=True, null=True)),
                ('breathing', models.CharField(blank=True, max_length=200, null=True)),
                ('normal_breathing', models.TextField(blank=True, null=True)),
                ('abnormal_breathing', models.CharField(blank=True, max_length=200, null=True)),
                ('circulating', models.CharField(blank=True, max_length=200, null=True)),
                ('normal_circulating', models.TextField(blank=True, null=True)),
                ('abnormal_circulating', models.CharField(blank=True, max_length=200, null=True)),
                ('gcs', models.CharField(blank=True, max_length=200, null=True)),
                ('rbg', models.CharField(blank=True, max_length=200, null=True)),
                ('pupil', models.CharField(blank=True, max_length=200, null=True)),
                ('pain_score', models.CharField(blank=True, max_length=200, null=True)),
                ('avpu', models.CharField(blank=True, max_length=200, null=True)),
                ('exposure', models.CharField(blank=True, max_length=200, null=True)),
                ('normal_exposure', models.CharField(blank=True, max_length=200, null=True)),
                ('abnormal_exposure', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicChiefComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_complaint', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.healthrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientvisits')),
            ],
        ),
    ]
