# Generated by Django 4.2.9 on 2024-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_rename_counselor_counseling_data_recorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='transport_model',
            field=models.CharField(blank=True, choices=[('Ground Ambulance', 'Ground Ambulance'), ('Air Ambulance', 'Air Ambulance'), ('Private Vehicle', 'Private Vehicle'), ('Self Transport', 'Self Transport'), ('Company Walking', 'Company Walking'), ('Walking', 'Walking'), ('Motorcycle', 'Motorcycle'), ('Others', 'Others'), ('Unknown', 'Unknown')], default='Ground Ambulance', max_length=50, null=True),
        ),
    ]
