# Generated by Django 4.2.9 on 2024-06-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_alter_referral_transport_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company', max_length=255)),
                ('registration_number', models.CharField(help_text='Company registration number', max_length=100, unique=True)),
                ('address', models.TextField(help_text='Address of the company')),
                ('city', models.CharField(help_text='City where the company is located', max_length=100)),
                ('state', models.CharField(help_text='State where the company is located', max_length=100)),
                ('country', models.CharField(help_text='Country where the company is located', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal code of the company', max_length=20)),
                ('phone_number', models.CharField(help_text='Contact phone number of the company', max_length=20)),
                ('email', models.EmailField(help_text='Email address of the company', max_length=254, unique=True)),
                ('website', models.URLField(blank=True, help_text='Website URL of the company', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicineinventory',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notificationmedicine',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsultationNotification',
        ),
        migrations.DeleteModel(
            name='MedicineInventory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationMedicine',
        ),
    ]
