# Generated by Django 4.2.9 on 2024-06-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_imagingrecord_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingrecord',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='laboratoryorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='total_price',
        ),
    ]
