# Generated by Django 4.2.9 on 2025-01-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_secondaryphysicalexamination_abnormal_heent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceactivity',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_activities', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='ambulanceroute',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_routes', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='ambulancevehicleorder',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_vehicle_orders', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='category',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='chiefcomplaint',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_complaints', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='clients',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='clinicchiefcomplaint',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_chief_complaints', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='cliniccompany',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_companies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='clinicprimaryphysicalexamination',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_primary_examinations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='clinicsecondaryphysicalexamination',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_secondary_examinations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='company',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='country',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='deductionorganization',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_organizations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='diseaserecode',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='employee',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_deductions', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_maintenance', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='expense',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='familymedicalhistory',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_medical_histories', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='governmentprogram',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='government_programs', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='grant',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='hospitalvehicle',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_vehicles', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_companies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='investment',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='medicineroute',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_routes', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='medicineunitmeasure',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_unit_measures', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='pathodologyrecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology_records', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patienthealthcondition',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_health_conditions', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patientlifestylebehavior',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_lifestyle_behaviors', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patientmedicationallergy',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_allergies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patients',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patientsurgery',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_surgeries', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='patientvisits',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='payment',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='prescriptionfrequency',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_frequencies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='primaryphysicalexamination',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_physical_examinations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='reagentusage',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reagent_usages', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteambulanceactivity',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_ambulance_activities', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteambulanceroute',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_ambulance_routes', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteambulancevehicleorder',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_ambulance_vehicle_orders', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotecompany',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_companies', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteconsultation',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_consultations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteequipment',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_equipments', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotehospitalvehicle',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_hospital_vehicles', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotemedicine',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_medicines', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotepatient',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_recorder', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotepatientvisits',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_patient_visits', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remotereagent',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_reagents', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='remoteservice',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_services', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='salarychangerecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_change_records', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='secondaryphysicalexamination',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_physical_examinations', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='service',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='clinic.staffs'),
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_histories', to='clinic.staffs'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_records', to='clinic.staffs'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='source_location',
            field=models.CharField(default='DIVINE TIS Mobile medical clinic', help_text='Source location of the patient', max_length=255),
        ),
    ]
