# Generated by Django 4.2.9 on 2025-01-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_ambulanceactivity_data_recorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='data_recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.staffs'),
        ),
    ]
