# Generated by Django 4.2.9 on 2025-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_diagnosis_data_recorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='mct_number',
            field=models.CharField(blank=True, help_text='Medical Council of Tanzania (MCT) Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload digital signature', null=True, upload_to='signatures/'),
        ),
    ]
