# Generated by Django 4.2.9 on 2025-05-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_staffs_mct_number_staffs_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationnotes',
            name='nature_of_current_illness',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='pathology',
        ),
        migrations.RemoveField(
            model_name='consultationnotes',
            name='type_of_illness',
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='allergy_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='doctor_plan_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='known_comorbidities_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='physical_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationnotes',
            name='review_of_systems',
            field=models.TextField(blank=True, null=True),
        ),
    ]
