# Generated by Django 4.2.9 on 2025-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0023_remove_consultationnotes_nature_of_current_illness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='patients',
            name='nida_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='insurance_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patients',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
