# Generated by Django 4.2.9 on 2025-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0024_remove_patients_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
