# Generated by Django 4.2.9 on 2025-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0025_alter_patients_insurance_name_alter_staffs_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dividable',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dividing_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest divisible unit in mg or ml, e.g., 125', null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_dividable',
            field=models.BooleanField(default=False, help_text='Is this drug divisible in smaller units?'),
        ),
    ]
