# Generated by Django 4.2.9 on 2025-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0026_remove_medicine_dividable_medicine_dividing_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotemedicine',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='remotemedicine',
            name='dividable',
        ),
        migrations.RemoveField(
            model_name='remotemedicine',
            name='total_buying_price',
        ),
        migrations.RemoveField(
            model_name='remotemedicine',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='remotemedicine',
            name='dividing_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest divisible unit in mg or ml, e.g., 125', null=True),
        ),
        migrations.AddField(
            model_name='remotemedicine',
            name='is_clinic_stock',
            field=models.BooleanField(default=True, help_text='Is this drug part of clinic stock?'),
        ),
        migrations.AddField(
            model_name='remotemedicine',
            name='is_dividable',
            field=models.BooleanField(default=False, help_text='Is this drug divisible in smaller units?'),
        ),
        migrations.AddField(
            model_name='remotemedicine',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0, help_text='Minimum threshold before restocking'),
        ),
        migrations.AlterField(
            model_name='remotemedicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remotemedicine',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotemedicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
