# Generated by Django 4.2.9 on 2025-07-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0027_remove_remotemedicine_buying_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='consultation_number',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='nature_of_current_illness',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='pathology',
        ),
        migrations.RemoveField(
            model_name='remoteconsultationnotes',
            name='type_of_illness',
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='allergy_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='doctor_plan_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='known_comorbidities_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='physical_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remoteconsultationnotes',
            name='review_of_systems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remoteconsultationnotes',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits'),
        ),
    ]
