# Generated by Django 4.2.9 on 2025-07-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0029_remove_clinicprimaryphysicalexamination_data_recorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteImagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imaging_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_imaging_records', to='clinic.staffs')),
                ('imaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.remotepatientvisits')),
            ],
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='Founded',
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='Notes',
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='data_recorder',
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='headquarters',
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='remotecompany',
            name='sector',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
