# Generated by Django 4.2.9 on 2024-05-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0080_order_type_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotepatient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
